seata:
  application-id: applicationName
  tx-service-group: my_test_tx_group
  client:
    rm:
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
      default-global-transaction-timeout: 60000
    undo:
      data-validation: true
      log-serialization: protobuf
      log-table: undo_log
      only-care-update-columns: true
      compress:
        enable: false
        type: zip
        threshold: 64k
    load-balance:
      type: RandomLoadBalance
      virtual-nodes: 10
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  transport:
    heartbeat: true
    serialization: seata
    compressor: none
  config:
    type: file # file, nacos
    nacos:
      namespace: ""
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: ""
      password: ""
      data-id: seata.properties
  registry:
    type: file # file, nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: "SEATA_GROUP"
      namespace: ""
      username: ""
      password: ""